---
title: "Week 4 Lab: Geoms and Aesthetic Mappings"
author: "Daniel Lip, Pierre Chan, Howard Yeo, Joel Koh, Jolie Yeo, Danish Dol, Sarah Loo"
format: html
editor: visual
---

# 1 Visualizing the Distribution of Travelers on the Titanic

##  1.1 Bar Chart of Travelers by Class
```{r}
#| label: Task 1.1

library(tidyverse)
library(ggplot2)

titanic_cat <- function(...) {
  ggplot2::labs(
    x = "",
    y = "",
    title = "Titanic Travelers by Class",
    caption = 'Source: Encylopedia Titanica (2023)',
    ...
  )
}

titanic_data <- read_csv("titanic.csv")
ggplot(titanic_data, aes(y=class)) +
  geom_bar(width=0.5,fill=NA, color = "black") +
  geom_text(stat = "count", aes(label = ..count..), hjust = -0.2) +
  titanic_cat() +
  theme(
    axis.text.x = element_blank(),       # Hide x-axis text
    axis.ticks.x = element_blank(),      # Hide x-axis ticks
    plot.title = element_text(hjust = 0.5)  # Center the title
  ) +
  xlim(0, 950) 

```

##  1.2 Dodged Bar Chart of Travelers by Class and Survival

```{r}
#| label: Task 1.2
ggplot(titanic_data, aes(y = class, fill = survived)) +
  geom_bar(position = "dodge") +
  geom_text(
    aes(label = after_stat(count), color = survived),  # Match label color to survival
    stat = "count",
    position = position_dodge(width = 0.9),
    hjust = -0.2,
    size = 3,
    fontface = "bold"
  ) +
  titanic_cat(fill = "Survived") +
  coord_cartesian(clip = "off") +
  scale_fill_manual(values = c("FALSE" = "salmon", "TRUE" = "turquoise")) +
  scale_color_manual(values = c("FALSE" = "salmon", "TRUE" = "turquoise")) +  # Label colors
  theme_minimal()
```

## 1.3 Mosaic Plot

```{r}

```